spring:
  application:
    name: security

  security:
    user:
      name: user
      password: password

logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org:
      springframework:
        security: trace
